/* global use, db */
// MongoDB Playground Seed Script
// How to use:
// 1) Ensure you're connected to your MongoDB cluster in VS Code (MongoDB extension)
// 2) Change the database name below if needed
// 3) Run this file (Play ▶) to insert dummy data

// Select the database to use (CHANGE THIS if your DB name is different)
use('test');

// Optional: Clean existing docs by id to avoid duplicate key errors on re-run
// db.getCollection('colleges').deleteMany({ id: { $in: [
//   'col-mumbai-inst', 'col-nagpur-univ', 'col-nashik-univ', 'col-aurangabad-univ',
//   'col-coimbatore-inst', 'col-salem-univ', 'col-tiruchy-univ', 'col-vellore-inst',
//   'col-mysore-univ', 'col-mangalore-univ', 'col-belgaum-univ', 'col-hubli-inst',
//   'col-rajkot-univ', 'col-surat-univ', 'col-vadodara-inst', 'col-bhavnagar-univ',
//   'col-durgapur-univ', 'col-siliguri-univ', 'col-burdwan-univ', 'col-kalyani-univ'
// ]}});
// db.getCollection('courses').deleteMany({ id: { $in: [
//   'crs-mumbai-inst-ece-btech', 'crs-mumbai-inst-finance-mba', 'crs-nagpur-civil-btech', 'crs-nagpur-physics-msc',
//   'crs-nashik-mech-btech', 'crs-nashik-chem-msc', 'crs-aurangabad-pharma-bpharm', 'crs-aurangabad-bio-msc',
//   'crs-coimbatore-tex-btech', 'crs-coimbatore-math-msc', 'crs-salem-agri-btech', 'crs-salem-bot-msc',
//   'crs-tiruchy-metal-btech', 'crs-tiruchy-geo-msc', 'crs-vellore-biomed-btech', 'crs-vellore-micro-msc',
//   'crs-mysore-silk-btech', 'crs-mysore-zool-msc', 'crs-mangalore-marine-btech', 'crs-mangalore-env-msc',
//   'crs-belgaum-sugar-btech', 'crs-belgaum-stats-msc', 'crs-hubli-auto-btech', 'crs-hubli-comp-msc',
//   'crs-rajkot-petro-btech', 'crs-rajkot-econ-ma', 'crs-surat-diamond-btech', 'crs-surat-socio-ma',
//   'crs-vadodara-paint-btech', 'crs-vadodara-psych-ma', 'crs-bhavnagar-ship-btech', 'crs-bhavnagar-pol-ma',
//   'crs-durgapur-steel-btech', 'crs-durgapur-phil-ma', 'crs-siliguri-tea-btech', 'crs-siliguri-geo-ma',
//   'crs-burdwan-rice-btech', 'crs-burdwan-hist-ma', 'crs-kalyani-fish-btech', 'crs-kalyani-lang-ma'
// ]}});

// Insert Colleges
db.getCollection('colleges').insertMany([
  // Maharashtra Colleges
  {
    id: 'col-mumbai-inst',
    name: 'Mumbai Institute of Technology',
    description: 'Leading technical institute specializing in electronics and communication systems.',
    state: 'Maharashtra',
    district: 'Mumbai',
    website: 'https://www.mitindia.edu/',
    establishYear: 1965,
    type: 'Private',
    manegement: 'Private',
    universityName: 'Mumbai Institute of Technology',
    universityType: 'Deemed University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-nagpur-univ',
    name: 'Nagpur Central University',
    description: 'Central university known for its excellence in civil engineering and physical sciences.',
    state: 'Maharashtra',
    district: 'Nagpur',
    website: 'https://www.ncunagpur.ac.in/',
    establishYear: 1973,
    type: 'Public',
    manegement: 'Government',
    universityName: 'Nagpur Central University',
    universityType: 'Central University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-nashik-univ',
    name: 'Nashik Engineering College',
    description: 'Premier engineering college with strong focus on mechanical and chemical engineering.',
    state: 'Maharashtra',
    district: 'Nashik',
    website: 'https://www.necnashik.ac.in/',
    establishYear: 1980,
    type: 'Public',
    manegement: 'Government',
    universityName: 'Maharashtra State Technical University',
    universityType: 'Affiliated',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-aurangabad-univ',
    name: 'Dr. Babasaheb Ambedkar Marathwada University',
    description: 'State university offering diverse programs in pharmaceutical sciences and biotechnology.',
    state: 'Maharashtra',
    district: 'Aurangabad',
    website: 'https://www.bamu.ac.in/',
    establishYear: 1958,
    type: 'Public',
    manegement: 'Government',
    universityName: 'Dr. Babasaheb Ambedkar Marathwada University',
    universityType: 'State University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Tamil Nadu Colleges
  {
    id: 'col-coimbatore-inst',
    name: 'Coimbatore Institute of Technology',
    description: 'Technical institute renowned for textile engineering and applied mathematics.',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    website: 'https://www.citcoimbatore.ac.in/',
    establishYear: 1956,
    type: 'Private',
    manegement: 'Private',
    universityName: 'Anna University',
    universityType: 'Affiliated',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-salem-univ',
    name: 'Salem Agricultural University',
    description: 'Specialized university focusing on agricultural engineering and botanical sciences.',
    state: 'Tamil Nadu',
    district: 'Salem',
    website: 'https://www.sau.ac.in/',
    establishYear: 1971,
    type: 'Public',
    manegement: 'Government',
    universityName: 'Tamil Nadu Agricultural University',
    universityType: 'Agricultural University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-tiruchy-univ',
    name: 'National Institute of Technology Tiruchirappalli',
    description: 'Prestigious NIT known for metallurgical engineering and geological sciences.',
    state: 'Tamil Nadu',
    district: 'Tiruchirappalli',
    website: 'https://www.nitt.edu/',
    establishYear: 1964,
    type: 'Public',
    manegement: 'Government',
    universityName: 'NIT Tiruchirappalli',
    universityType: 'Institute of National Importance',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-vellore-inst',
    name: 'Vellore Institute of Technology',
    description: 'Private institute excelling in biomedical engineering and microbiology research.',
    state: 'Tamil Nadu',
    district: 'Vellore',
    website: 'https://www.vit.ac.in/',
    establishYear: 1984,
    type: 'Private',
    manegement: 'Private',
    universityName: 'VIT University',
    universityType: 'Deemed University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Karnataka Colleges
  {
    id: 'col-mysore-univ',
    name: 'University of Mysore',
    description: 'Historic university known for silk technology and zoological research.',
    state: 'Karnataka',
    district: 'Mysuru',
    website: 'https://www.uni-mysore.ac.in/',
    establishYear: 1916,
    type: 'Public',
    manegement: 'Government',
    universityName: 'University of Mysore',
    universityType: 'State University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-mangalore-univ',
    name: 'Mangalore University',
    description: 'Coastal university specializing in marine engineering and environmental sciences.',
    state: 'Karnataka',
    district: 'Mangaluru',
    website: 'https://www.mangaloreuniversity.ac.in/',
    establishYear: 1980,
    type: 'Public',
    manegement: 'Government',
    universityName: 'Mangalore University',
    universityType: 'State University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-belgaum-univ',
    name: 'KLE University Belgaum',
    description: 'Private university with expertise in sugar technology and statistical sciences.',
    state: 'Karnataka',
    district: 'Belgaum',
    website: 'https://www.kluniversity.in/',
    establishYear: 1963,
    type: 'Private',
    manegement: 'Private',
    universityName: 'KLE University',
    universityType: 'Deemed University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-hubli-inst',
    name: 'BVB College of Engineering Hubli',
    description: 'Engineering college renowned for automobile engineering and computer science.',
    state: 'Karnataka',
    district: 'Hubli',
    website: 'https://www.bvb.edu/',
    establishYear: 1947,
    type: 'Public',
    manegement: 'Government',
    universityName: 'Visvesvaraya Technological University',
    universityType: 'Affiliated',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Gujarat Colleges
  {
    id: 'col-rajkot-univ',
    name: 'Rajkot Technical University',
    description: 'Technical university specializing in petroleum engineering and economic studies.',
    state: 'Gujarat',
    district: 'Rajkot',
    website: 'https://www.rtu.ac.in/',
    establishYear: 1967,
    type: 'Public',
    manegement: 'Government',
    universityName: 'Gujarat Technological University',
    universityType: 'State Technical University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-surat-univ',
    name: 'Surat Diamond University',
    description: 'Specialized university focusing on diamond technology and sociological research.',
    state: 'Gujarat',
    district: 'Surat',
    website: 'https://www.sdu.ac.in/',
    establishYear: 1995,
    type: 'Private',
    manegement: 'Private',
    universityName: 'Surat Diamond University',
    universityType: 'Private University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-vadodara-inst',
    name: 'Maharaja Sayajirao University Vadodara',
    description: 'Premier institute known for paint technology and psychological research.',
    state: 'Gujarat',
    district: 'Vadodara',
    website: 'https://www.msubaroda.ac.in/',
    establishYear: 1949,
    type: 'Public',
    manegement: 'Government',
    universityName: 'Maharaja Sayajirao University',
    universityType: 'State University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-bhavnagar-univ',
    name: 'Bhavnagar Maritime University',
    description: 'Maritime university excelling in shipbuilding technology and political sciences.',
    state: 'Gujarat',
    district: 'Bhavnagar',
    website: 'https://www.bmu.ac.in/',
    establishYear: 1978,
    type: 'Public',
    manegement: 'Government',
    universityName: 'Gujarat Maritime University',
    universityType: 'State University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // West Bengal Colleges
  {
    id: 'col-durgapur-univ',
    name: 'National Institute of Technology Durgapur',
    description: 'NIT focusing on steel technology and philosophical studies.',
    state: 'West Bengal',
    district: 'Durgapur',
    website: 'https://www.nitdgp.ac.in/',
    establishYear: 1960,
    type: 'Public',
    manegement: 'Government',
    universityName: 'NIT Durgapur',
    universityType: 'Institute of National Importance',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-siliguri-univ',
    name: 'University of North Bengal',
    description: 'Regional university known for tea technology and geographical studies.',
    state: 'West Bengal',
    district: 'Siliguri',
    website: 'https://www.nbu.ac.in/',
    establishYear: 1962,
    type: 'Public',
    manegement: 'Government',
    universityName: 'University of North Bengal',
    universityType: 'State University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-burdwan-univ',
    name: 'Burdwan University',
    description: 'Agricultural university specializing in rice technology and historical research.',
    state: 'West Bengal',
    district: 'Burdwan',
    website: 'https://www.buruniv.ac.in/',
    establishYear: 1960,
    type: 'Public',
    manegement: 'Government',
    universityName: 'University of Burdwan',
    universityType: 'State University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'col-kalyani-univ',
    name: 'Kalyani University',
    description: 'Fisheries university excelling in aquaculture technology and language studies.',
    state: 'West Bengal',
    district: 'Kalyani',
    website: 'https://www.klyuniv.ac.in/',
    establishYear: 1960,
    type: 'Public',
    manegement: 'Government',
    universityName: 'University of Kalyani',
    universityType: 'State University',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]);

// Insert Courses (ensure dates are valid)
const now = new Date();
const in30Days = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
const in90Days = new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000);

db.getCollection('courses').insertMany([
  // Mumbai Institute of Technology Courses
  {
    id: 'crs-mumbai-inst-ece-btech',
    title: 'B.Tech Electronics & Communication Engineering',
    description: 'Advanced program in electronics with focus on communication systems and signal processing.',
    collegeId: 'col-mumbai-inst',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM, MHT-CET or JEE Main',
    fee: 185000,
    syllabusOutline: 'Signal Processing, Communication Systems, VLSI Design, Embedded Systems',
    isActive: true,
    applicationStart: now,
    applicationEnd: in30Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-mumbai-inst-finance-mba',
    title: 'MBA in Finance',
    description: 'Specialized MBA program focusing on financial markets and investment banking.',
    collegeId: 'col-mumbai-inst',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor degree with CAT/MAT/GMAT',
    fee: 325000,
    syllabusOutline: 'Financial Markets, Investment Banking, Risk Management, Corporate Finance',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Nagpur Central University Courses
  {
    id: 'crs-nagpur-civil-btech',
    title: 'B.Tech Civil Engineering',
    description: 'Infrastructure engineering program with emphasis on sustainable construction.',
    collegeId: 'col-nagpur-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM, MHT-CET or JEE Main',
    fee: 125000,
    syllabusOutline: 'Structural Engineering, Transportation, Hydraulics, Construction Management',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-nagpur-physics-msc',
    title: 'M.Sc Physics',
    description: 'Advanced physics program with specialization in condensed matter and quantum mechanics.',
    collegeId: 'col-nagpur-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Physics or related field',
    fee: 65000,
    syllabusOutline: 'Quantum Mechanics, Condensed Matter, Nuclear Physics, Research Methods',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Nashik Engineering College Courses
  {
    id: 'crs-nashik-mech-btech',
    title: 'B.Tech Mechanical Engineering',
    description: 'Mechanical engineering program with focus on automotive and manufacturing systems.',
    collegeId: 'col-nashik-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM, MHT-CET or JEE Main',
    fee: 135000,
    syllabusOutline: 'Thermodynamics, Manufacturing, Automotive Systems, CAD/CAM',
    isActive: true,
    applicationStart: now,
    applicationEnd: in30Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-nashik-chem-msc',
    title: 'M.Sc Chemistry',
    description: 'Chemistry program specializing in organic synthesis and analytical chemistry.',
    collegeId: 'col-nashik-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Chemistry or related field',
    fee: 55000,
    syllabusOutline: 'Organic Chemistry, Analytical Chemistry, Physical Chemistry, Instrumental Analysis',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Dr. Babasaheb Ambedkar Marathwada University Courses
  {
    id: 'crs-aurangabad-pharma-bpharm',
    title: 'Bachelor of Pharmacy',
    description: 'Comprehensive pharmacy program covering drug discovery and pharmaceutical analysis.',
    collegeId: 'col-aurangabad-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCB, MHT-CET or NEET',
    fee: 165000,
    syllabusOutline: 'Pharmaceutical Chemistry, Pharmacology, Drug Analysis, Clinical Pharmacy',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-aurangabad-bio-msc',
    title: 'M.Sc Biotechnology',
    description: 'Advanced biotechnology program with focus on genetic engineering and bioinformatics.',
    collegeId: 'col-aurangabad-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Life Sciences or related field',
    fee: 85000,
    syllabusOutline: 'Genetic Engineering, Bioinformatics, Molecular Biology, Bioprocessing',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Coimbatore Institute of Technology Courses
  {
    id: 'crs-coimbatore-tex-btech',
    title: 'B.Tech Textile Engineering',
    description: 'Specialized textile engineering program covering fiber technology and fabric design.',
    collegeId: 'col-coimbatore-inst',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM, TNEA or JEE Main',
    fee: 155000,
    syllabusOutline: 'Fiber Technology, Fabric Design, Textile Chemistry, Quality Control',
    isActive: true,
    applicationStart: now,
    applicationEnd: in30Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-coimbatore-math-msc',
    title: 'M.Sc Applied Mathematics',
    description: 'Mathematics program with applications in engineering and computational sciences.',
    collegeId: 'col-coimbatore-inst',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Mathematics or related field',
    fee: 45000,
    syllabusOutline: 'Numerical Analysis, Applied Statistics, Mathematical Modeling, Computational Methods',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Salem Agricultural University Courses
  {
    id: 'crs-salem-agri-btech',
    title: 'B.Tech Agricultural Engineering',
    description: 'Agricultural engineering program focusing on farm mechanization and irrigation systems.',
    collegeId: 'col-salem-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM or PCB, TNEA or JEE Main',
    fee: 115000,
    syllabusOutline: 'Farm Mechanization, Irrigation Systems, Post Harvest Technology, Soil Engineering',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-salem-bot-msc',
    title: 'M.Sc Botany',
    description: 'Botany program with emphasis on plant physiology and agricultural applications.',
    collegeId: 'col-salem-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Botany or Life Sciences',
    fee: 35000,
    syllabusOutline: 'Plant Physiology, Plant Pathology, Agricultural Botany, Research Methods',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // National Institute of Technology Tiruchirappalli Courses
  {
    id: 'crs-tiruchy-metal-btech',
    title: 'B.Tech Metallurgical & Materials Engineering',
    description: 'Metallurgy program covering advanced materials and processing technologies.',
    collegeId: 'col-tiruchy-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM, JEE Main (NIT cutoff)',
    fee: 125000,
    syllabusOutline: 'Materials Science, Metallurgy, Nanotechnology, Materials Characterization',
    isActive: true,
    applicationStart: now,
    applicationEnd: in30Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-tiruchy-geo-msc',
    title: 'M.Sc Geology',
    description: 'Geological sciences program with focus on mineral exploration and environmental geology.',
    collegeId: 'col-tiruchy-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Geology or Earth Sciences',
    fee: 55000,
    syllabusOutline: 'Mineral Exploration, Environmental Geology, Petrology, Structural Geology',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Vellore Institute of Technology Courses
  {
    id: 'crs-vellore-biomed-btech',
    title: 'B.Tech Biomedical Engineering',
    description: 'Biomedical engineering program combining engineering principles with medical applications.',
    collegeId: 'col-vellore-inst',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM or PCB, VITEEE or JEE Main',
    fee: 195000,
    syllabusOutline: 'Medical Instrumentation, Biomaterials, Medical Imaging, Prosthetics',
    isActive: true,
    applicationStart: now,
    applicationEnd: in30Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-vellore-micro-msc',
    title: 'M.Sc Microbiology',
    description: 'Microbiology program with applications in medical and industrial microbiology.',
    collegeId: 'col-vellore-inst',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Microbiology or Life Sciences',
    fee: 125000,
    syllabusOutline: 'Medical Microbiology, Industrial Microbiology, Immunology, Molecular Microbiology',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // University of Mysore Courses
  {
    id: 'crs-mysore-silk-btech',
    title: 'B.Tech Silk Technology',
    description: 'Specialized program in silk production technology and sericulture engineering.',
    collegeId: 'col-mysore-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM or PCB, KCET or state entrance',
    fee: 95000,
    syllabusOutline: 'Sericulture, Silk Processing, Textile Technology, Quality Control',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-mysore-zool-msc',
    title: 'M.Sc Zoology',
    description: 'Zoology program with focus on animal behavior and conservation biology.',
    collegeId: 'col-mysore-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Zoology or Life Sciences',
    fee: 25000,
    syllabusOutline: 'Animal Behavior, Conservation Biology, Ecology, Animal Physiology',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Mangalore University Courses
  {
    id: 'crs-mangalore-marine-btech',
    title: 'B.Tech Marine Engineering',
    description: 'Marine engineering program focusing on ship systems and ocean engineering.',
    collegeId: 'col-mangalore-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM, KCET or JEE Main',
    fee: 165000,
    syllabusOutline: 'Ship Systems, Ocean Engineering, Marine Propulsion, Naval Architecture',
    isActive: true,
    applicationStart: now,
    applicationEnd: in30Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-mangalore-env-msc',
    title: 'M.Sc Environmental Science',
    description: 'Environmental science program with focus on coastal and marine ecosystems.',
    collegeId: 'col-mangalore-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Environmental Science or related field',
    fee: 45000,
    syllabusOutline: 'Marine Ecology, Environmental Monitoring, Pollution Control, Coastal Management',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // KLE University Belgaum Courses
  {
    id: 'crs-belgaum-sugar-btech',
    title: 'B.Tech Sugar Technology',
    description: 'Specialized program in sugar production technology and food processing.',
    collegeId: 'col-belgaum-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM or PCB, KCET or entrance exam',
    fee: 145000,
    syllabusOutline: 'Sugar Processing, Food Technology, Quality Control, Industrial Management',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-belgaum-stats-msc',
    title: 'M.Sc Statistics',
    description: 'Statistics program with applications in data science and quality control.',
    collegeId: 'col-belgaum-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Statistics or Mathematics',
    fee: 55000,
    syllabusOutline: 'Statistical Inference, Data Science, Quality Control, Applied Statistics',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // BVB College of Engineering Hubli Courses
  {
    id: 'crs-hubli-auto-btech',
    title: 'B.Tech Automobile Engineering',
    description: 'Automobile engineering program covering vehicle design and automotive systems.',
    collegeId: 'col-hubli-inst',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM, KCET or JEE Main',
    fee: 125000,
    syllabusOutline: 'Vehicle Design, Automotive Systems, Engine Technology, Electric Vehicles',
    isActive: true,
    applicationStart: now,
    applicationEnd: in30Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-hubli-comp-msc',
    title: 'M.Sc Computer Science',
    description: 'Computer science program with focus on algorithms and software engineering.',
    collegeId: 'col-hubli-inst',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Computer Science or related field',
    fee: 75000,
    syllabusOutline: 'Advanced Algorithms, Software Engineering, Database Systems, Machine Learning',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Rajkot Technical University Courses
  {
    id: 'crs-rajkot-petro-btech',
    title: 'B.Tech Petroleum Engineering',
    description: 'Petroleum engineering program covering oil exploration and refining processes.',
    collegeId: 'col-rajkot-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM, GUJCET or JEE Main',
    fee: 175000,
    syllabusOutline: 'Oil Exploration, Drilling Technology, Refining Processes, Reservoir Engineering',
    isActive: true,
    applicationStart: now,
    applicationEnd: in30Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-rajkot-econ-ma',
    title: 'MA Economics',
    description: 'Economics program with focus on industrial economics and regional development.',
    collegeId: 'col-rajkot-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Economics or related field',
    fee: 35000,
    syllabusOutline: 'Industrial Economics, Regional Development, Economic Policy, Statistical Methods',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Surat Diamond University Courses
  {
    id: 'crs-surat-diamond-btech',
    title: 'B.Tech Diamond Technology',
    description: 'Unique program in diamond cutting technology and jewelry design.',
    collegeId: 'col-surat-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM, portfolio review and entrance test',
    fee: 225000,
    syllabusOutline: 'Diamond Cutting, Jewelry Design, Gemology, CAD for Jewelry',
    isActive: true,
    applicationStart: now,
    applicationEnd: in30Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-surat-socio-ma',
    title: 'MA Sociology',
    description: 'Sociology program with focus on industrial society and urban development.',
    collegeId: 'col-surat-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Sociology or Social Sciences',
    fee: 45000,
    syllabusOutline: 'Industrial Sociology, Urban Development, Social Research, Community Studies',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Maharaja Sayajirao University Vadodara Courses
  {
    id: 'crs-vadodara-paint-btech',
    title: 'B.Tech Paint Technology',
    description: 'Specialized program in paint and coating technology for industrial applications.',
    collegeId: 'col-vadodara-inst',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM, GUJCET or JEE Main',
    fee: 135000,
    syllabusOutline: 'Paint Chemistry, Coating Technology, Surface Science, Quality Testing',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-vadodara-psych-ma',
    title: 'MA Psychology',
    description: 'Psychology program with specializations in clinical and industrial psychology.',
    collegeId: 'col-vadodara-inst',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Psychology or related field',
    fee: 55000,
    syllabusOutline: 'Clinical Psychology, Industrial Psychology, Research Methods, Counseling',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Bhavnagar Maritime University Courses
  {
    id: 'crs-bhavnagar-ship-btech',
    title: 'B.Tech Naval Architecture & Shipbuilding',
    description: 'Shipbuilding engineering program covering vessel design and marine structures.',
    collegeId: 'col-bhavnagar-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM, GUJCET or JEE Main',
    fee: 165000,
    syllabusOutline: 'Ship Design, Marine Structures, Hydrodynamics, Shipyard Management',
    isActive: true,
    applicationStart: now,
    applicationEnd: in30Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-bhavnagar-pol-ma',
    title: 'MA Political Science',
    description: 'Political science program with focus on maritime law and international relations.',
    collegeId: 'col-bhavnagar-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Political Science or related field',
    fee: 35000,
    syllabusOutline: 'Maritime Law, International Relations, Public Administration, Political Theory',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // National Institute of Technology Durgapur Courses
  {
    id: 'crs-durgapur-steel-btech',
    title: 'B.Tech Steel Technology',
    description: 'Steel technology program covering iron and steel production processes.',
    collegeId: 'col-durgapur-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM, JEE Main (NIT cutoff)',
    fee: 125000,
    syllabusOutline: 'Iron Making, Steel Making, Rolling Technology, Quality Control',
    isActive: true,
    applicationStart: now,
    applicationEnd: in30Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-durgapur-phil-ma',
    title: 'MA Philosophy',
    description: 'Philosophy program with focus on ethics and philosophy of technology.',
    collegeId: 'col-durgapur-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Philosophy or Humanities',
    fee: 25000,
    syllabusOutline: 'Ethics, Philosophy of Technology, Logic, Indian Philosophy',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // University of North Bengal Courses
  {
    id: 'crs-siliguri-tea-btech',
    title: 'B.Tech Tea Technology',
    description: 'Specialized program in tea production technology and plantation management.',
    collegeId: 'col-siliguri-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM or PCB, WBJEE or state entrance',
    fee: 85000,
    syllabusOutline: 'Tea Processing, Plantation Management, Quality Control, Food Technology',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-siliguri-geo-ma',
    title: 'MA Geography',
    description: 'Geography program with focus on mountain geography and environmental studies.',
    collegeId: 'col-siliguri-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Geography or related field',
    fee: 35000,
    syllabusOutline: 'Mountain Geography, Environmental Geography, Remote Sensing, GIS',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Burdwan University Courses
  {
    id: 'crs-burdwan-rice-btech',
    title: 'B.Tech Rice Technology',
    description: 'Agricultural engineering program specializing in rice processing and cultivation.',
    collegeId: 'col-burdwan-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM or PCB, WBJEE or state entrance',
    fee: 75000,
    syllabusOutline: 'Rice Processing, Agricultural Machinery, Post Harvest Technology, Quality Control',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-burdwan-hist-ma',
    title: 'MA History',
    description: 'History program with specialization in medieval and modern Indian history.',
    collegeId: 'col-burdwan-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in History or related field',
    fee: 25000,
    syllabusOutline: 'Medieval History, Modern Indian History, Historical Methods, Archaeology',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Kalyani University Courses
  {
    id: 'crs-kalyani-fish-btech',
    title: 'B.Tech Fisheries Technology',
    description: 'Fisheries engineering program covering aquaculture and fish processing technology.',
    collegeId: 'col-kalyani-univ',
    programType: 'Undergraduate',
    duration: '4 years',
    eligibilityCriteria: '12th with PCM or PCB, WBJEE or state entrance',
    fee: 85000,
    syllabusOutline: 'Aquaculture, Fish Processing, Marine Biology, Fisheries Management',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'crs-kalyani-lang-ma',
    title: 'MA Linguistics',
    description: 'Linguistics program with focus on regional languages and computational linguistics.',
    collegeId: 'col-kalyani-univ',
    programType: 'Postgraduate',
    duration: '2 years',
    eligibilityCriteria: 'Bachelor in Languages or Humanities',
    fee: 35000,
    syllabusOutline: 'Computational Linguistics, Regional Languages, Phonetics, Language Documentation',
    isActive: true,
    applicationStart: now,
    applicationEnd: in90Days,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]);

console.log('Seeded colleges and courses successfully.');